import readXlsxFile from 'read-excel-file/node'
import { parseTimetable } from './nhmt-parser'

describe('nhmt parsing', () => {
	it('should parse', async () => {
		const sheets = await readXlsxFile(
			'./src/services/nhmt/example/1_2026-2027.xlsx',
		)
		const parsed = parseTimetable(sheets[0].data)
		parsed.entries = parsed.entries.slice(0, 10)
		expect(parsed).toMatchInlineSnapshot(`
		{
		  "dropdown": {
		    "clientTypes": [
		      {
		        "type": 0,
		      },
		    ],
		    "courses": [
		      {
		        "course": 1,
		      },
		      {
		        "course": 2,
		      },
		    ],
		    "faculties": [
		      {
		        "id": 1,
		        "name": "ССА",
		      },
		      {
		        "id": 2,
		        "name": "ИС",
		      },
		      {
		        "id": 3,
		        "name": "ПО",
		      },
		      {
		        "id": 4,
		        "name": "МЭТО",
		      },
		      {
		        "id": 5,
		        "name": "АТП",
		      },
		      {
		        "id": 6,
		        "name": "ТЭЭО",
		      },
		      {
		        "id": 7,
		        "name": "ТОВ",
		      },
		      {
		        "id": 8,
		        "name": "ТАК",
		      },
		      {
		        "id": 9,
		        "name": "ФАРМ",
		      },
		      {
		        "id": 10,
		        "name": "ТД",
		      },
		      {
		        "id": 11,
		        "name": "ЛОГ",
		      },
		      {
		        "id": 12,
		        "name": "ИН",
		      },
		      {
		        "id": 13,
		        "name": "ЭН",
		      },
		      {
		        "id": 14,
		        "name": "КИН",
		      },
		    ],
		    "formsOfEducation": [
		      {
		        "id": 1,
		        "name": "Дневное отделение",
		      },
		    ],
		    "groups": [
		      {
		        "course": 1,
		        "facultyId": 1,
		        "id": 3,
		        "name": "26-СО-130",
		        "shortName": "1-ССА",
		      },
		      {
		        "course": 1,
		        "facultyId": 2,
		        "id": 4,
		        "name": "26-ИО-129",
		        "shortName": "1-ИС",
		      },
		      {
		        "course": 1,
		        "facultyId": 3,
		        "id": 5,
		        "name": "1-ПО",
		        "shortName": "1-ПО",
		      },
		      {
		        "course": 1,
		        "facultyId": 4,
		        "id": 6,
		        "name": "26-МО-030",
		        "shortName": "11-МЭТО",
		      },
		      {
		        "course": 1,
		        "facultyId": 4,
		        "id": 7,
		        "name": "26-МО-130",
		        "shortName": "12-МЭТО",
		      },
		      {
		        "course": 1,
		        "facultyId": 5,
		        "id": 8,
		        "name": "26-АО-030",
		        "shortName": "11-АТП",
		      },
		      {
		        "course": 1,
		        "facultyId": 5,
		        "id": 9,
		        "name": "26-АО-130",
		        "shortName": "12-АТП",
		      },
		      {
		        "course": 1,
		        "facultyId": 6,
		        "id": 10,
		        "name": "26-ЭО-130",
		        "shortName": "1-ТЭЭО",
		      },
		      {
		        "course": 1,
		        "facultyId": 7,
		        "id": 11,
		        "name": "26-ХО-030",
		        "shortName": "11-ТОВ",
		      },
		      {
		        "course": 1,
		        "facultyId": 7,
		        "id": 12,
		        "name": "26-ХО-130",
		        "shortName": "12-ТОВ",
		      },
		      {
		        "course": 1,
		        "facultyId": 8,
		        "id": 13,
		        "name": "26-ТАО-130",
		        "shortName": "1-ТАК",
		      },
		      {
		        "course": 1,
		        "facultyId": 9,
		        "id": 14,
		        "name": "26-ФО-029",
		        "shortName": "11-ФАРМ",
		      },
		      {
		        "course": 1,
		        "facultyId": 9,
		        "id": 15,
		        "name": "26-ФО-129",
		        "shortName": "12-ФАРМ",
		      },
		      {
		        "course": 1,
		        "facultyId": 9,
		        "id": 16,
		        "name": "26-ФО-229",
		        "shortName": "13-ФАРМ",
		      },
		      {
		        "course": 1,
		        "facultyId": 10,
		        "id": 17,
		        "name": "26-ТО-129",
		        "shortName": "1-ТД",
		      },
		      {
		        "course": 1,
		        "facultyId": 11,
		        "id": 18,
		        "name": "26-ЛО-229",
		        "shortName": "12-ЛОГ",
		      },
		      {
		        "course": 1,
		        "facultyId": 11,
		        "id": 19,
		        "name": "26-ЛО-329",
		        "shortName": "13-ЛОГ",
		      },
		      {
		        "course": 1,
		        "facultyId": 12,
		        "id": 20,
		        "name": "26-ОИН-128",
		        "shortName": "11-ИН",
		      },
		      {
		        "course": 1,
		        "facultyId": 13,
		        "id": 21,
		        "name": "26-ЭН-028",
		        "shortName": "11-ЭН",
		      },
		      {
		        "course": 1,
		        "facultyId": 13,
		        "id": 22,
		        "name": "26-ЭН-128",
		        "shortName": "12-ЭН",
		      },
		      {
		        "course": 1,
		        "facultyId": 13,
		        "id": 23,
		        "name": "26-ЭН-228",
		        "shortName": "13-ЭН",
		      },
		      {
		        "course": 1,
		        "facultyId": 14,
		        "id": 24,
		        "name": "26-КИН-128",
		        "shortName": "11-КИН",
		      },
		      {
		        "course": 2,
		        "facultyId": 1,
		        "id": 25,
		        "name": "25-СО-129",
		        "shortName": "2-ССА",
		      },
		      {
		        "course": 2,
		        "facultyId": 2,
		        "id": 26,
		        "name": "25-ИО-029",
		        "shortName": "21-ИС",
		      },
		      {
		        "course": 2,
		        "facultyId": 2,
		        "id": 27,
		        "name": "25-ИО-129",
		        "shortName": "22-ИС",
		      },
		      {
		        "course": 2,
		        "facultyId": 4,
		        "id": 28,
		        "name": "25-МО-029",
		        "shortName": "21-МЭТО",
		      },
		      {
		        "course": 2,
		        "facultyId": 4,
		        "id": 29,
		        "name": "25-МО-129",
		        "shortName": "22-МЭТО",
		      },
		      {
		        "course": 2,
		        "facultyId": 5,
		        "id": 30,
		        "name": "25-АО-129",
		        "shortName": "2-АТП",
		      },
		      {
		        "course": 2,
		        "facultyId": 6,
		        "id": 31,
		        "name": "25-ЭО-129",
		        "shortName": "2-ТЭЭО",
		      },
		      {
		        "course": 2,
		        "facultyId": 7,
		        "id": 32,
		        "name": "25-ХО-029",
		        "shortName": "21-ТОВ",
		      },
		      {
		        "course": 2,
		        "facultyId": 7,
		        "id": 33,
		        "name": "25-ХО-129",
		        "shortName": "22-ТОВ",
		      },
		      {
		        "course": 2,
		        "facultyId": 8,
		        "id": 34,
		        "name": "25-ТАО-128",
		        "shortName": "2-ТАК",
		      },
		      {
		        "course": 2,
		        "facultyId": 9,
		        "id": 35,
		        "name": "25-ФО-028",
		        "shortName": "21-ФАРМ",
		      },
		      {
		        "course": 2,
		        "facultyId": 9,
		        "id": 36,
		        "name": "25-ФО-128",
		        "shortName": "22-ФАРМ",
		      },
		      {
		        "course": 2,
		        "facultyId": 9,
		        "id": 37,
		        "name": "25-ФО-228",
		        "shortName": "23-ФАРМ",
		      },
		      {
		        "course": 2,
		        "facultyId": 10,
		        "id": 38,
		        "name": "25-ТО-128",
		        "shortName": "2-ТД",
		      },
		      {
		        "course": 2,
		        "facultyId": 11,
		        "id": 39,
		        "name": "25-ЛО-228",
		        "shortName": "22-ЛОГ",
		      },
		      {
		        "course": 2,
		        "facultyId": 11,
		        "id": 40,
		        "name": "25-ЛО-328",
		        "shortName": "23-ЛОГ",
		      },
		      {
		        "course": 2,
		        "facultyId": 12,
		        "id": 41,
		        "name": "25-ОИН-127",
		        "shortName": "2-ИН",
		      },
		      {
		        "course": 2,
		        "facultyId": 13,
		        "id": 42,
		        "name": "25-ЭН-027",
		        "shortName": "21-ЭН",
		      },
		      {
		        "course": 2,
		        "facultyId": 13,
		        "id": 43,
		        "name": "25-ЭН-127",
		        "shortName": "22-ЭН",
		      },
		      {
		        "course": 2,
		        "facultyId": 14,
		        "id": 44,
		        "name": "25-КИН-127",
		        "shortName": "2-КИН",
		      },
		    ],
		  },
		  "entries": [
		    {
		      "auditoriumName": "У 208",
		      "auditoriumShortName": "208",
		      "building": "У",
		      "dayOfWeek": 1,
		      "discipline": "Русский язык",
		      "end": "09:40",
		      "groupId": 3,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Иванова КА",
		    },
		    {
		      "auditoriumName": "303 корп3",
		      "auditoriumShortName": "303",
		      "building": "корп3",
		      "dayOfWeek": 1,
		      "discipline": "Русский язык",
		      "end": "09:40",
		      "groupId": 4,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Таймаскина ОВ",
		    },
		    {
		      "auditoriumName": "У 35",
		      "auditoriumShortName": "35",
		      "building": "У",
		      "dayOfWeek": 1,
		      "discipline": "Математика",
		      "end": "09:40",
		      "groupId": 5,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Зайламова ОВ",
		    },
		    {
		      "auditoriumName": "У 201",
		      "auditoriumShortName": "201",
		      "building": "У",
		      "dayOfWeek": 1,
		      "discipline": "Математика",
		      "end": "09:40",
		      "groupId": 6,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Комарова НА",
		    },
		    {
		      "auditoriumName": "У 21",
		      "auditoriumShortName": "21",
		      "building": "У",
		      "dayOfWeek": 1,
		      "discipline": "Математика",
		      "end": "09:40",
		      "groupId": 7,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Народова КИ",
		    },
		    {
		      "auditoriumName": "305 корп3",
		      "auditoriumShortName": "305",
		      "building": "корп3",
		      "dayOfWeek": 1,
		      "discipline": "Физика",
		      "end": "09:40",
		      "groupId": 8,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Димитриева ЕВ",
		    },
		    {
		      "auditoriumName": "306 корп3",
		      "auditoriumShortName": "306",
		      "building": "корп3",
		      "dayOfWeek": 1,
		      "discipline": "География",
		      "end": "09:40",
		      "groupId": 9,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Жилов АВ",
		    },
		    {
		      "auditoriumName": "П 30",
		      "auditoriumShortName": "30",
		      "building": "П",
		      "dayOfWeek": 1,
		      "discipline": "Информатика",
		      "end": "09:40",
		      "groupId": 10,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Маркова МН",
		    },
		    {
		      "auditoriumName": "У 30",
		      "auditoriumShortName": "30",
		      "building": "У",
		      "dayOfWeek": 1,
		      "discipline": "Обществознание",
		      "end": "09:40",
		      "groupId": 11,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Федотов Г.В.",
		    },
		    {
		      "auditoriumName": "с/з",
		      "auditoriumShortName": "с/з",
		      "building": "",
		      "dayOfWeek": 1,
		      "discipline": "Физ.культура",
		      "end": "09:40",
		      "groupId": 12,
		      "lessonNumber": 1,
		      "start": "08:00",
		      "subgroup": 0,
		      "teacherName": "Григорьев СЮ",
		    },
		  ],
		  "semesterStart": 2026-08-31T21:00:00.000Z,
		}
	`)
	})
})
